//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.7 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2018.07.11 at 07:10:14 PM CEST 
//


package com.insane.users;

import javax.xml.bind.annotation.XmlEnum;
import javax.xml.bind.annotation.XmlEnumValue;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for typeOfSubscription.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * <p>
 * <pre>
 * &lt;simpleType name="typeOfSubscription">
 *   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *     &lt;enumeration value="Subscribed"/>
 *     &lt;enumeration value="Privileged"/>
 *     &lt;enumeration value="None"/>
 *   &lt;/restriction>
 * &lt;/simpleType>
 * </pre>
 * 
 */
@XmlType(name = "typeOfSubscription")
@XmlEnum
public enum TypeOfSubscription {

    @XmlEnumValue("Subscribed")
    SUBSCRIBED("Subscribed"),
    @XmlEnumValue("Privileged")
    PRIVILEGED("Privileged"),
    @XmlEnumValue("None")
    NONE("None");
    private final String value;

    TypeOfSubscription(String v) {
        value = v;
    }

    public String value() {
        return value;
    }

    public static TypeOfSubscription fromValue(String v) {
        for (TypeOfSubscription c: TypeOfSubscription.values()) {
            if (c.value.equals(v)) {
                return c;
            }
        }
        throw new IllegalArgumentException(v);
    }

}
